#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

do_setup_live_environment()
{
  chmod 0440 /etc/sudoers 
  mkdir -p /home/$LIVE_USERNAME
  groupadd admin
  useradd -u 1000 -g users -G storage,optical,audio,video,network,wheel,power,hal,lp,admin -d /home/$LIVE_USERNAME $LIVE_USERNAME
  passwd -d $LIVE_USERNAME &> /dev/null
  chown synth /home/$LIVE_USERNAME
  su -c "cp -r /etc/skel/.[a-zA-Z0-9]* /home/$LIVE_USERNAME/" $LIVE_USERNAME
  su -c "cp -r /etc/skel/* /home/$LIVE_USERNAME/" $LIVE_USERNAME

  #are we running in virtualbox? if so, use the dummy backend for jack.
  #TODO this is proken in latest arch because net-tools is deprecated.
  #if [ "`route | grep 10.0.2.2`" != "" ]; then
  #  su -c "cp /home/$LIVE_USERNAME/.config/jack/dummy-conf.xml /home/$LIVE_USERNAME/.config/jack/conf.xml" $LIVE_USERNAME
  #fi
  #TODO detect firewire and other audio cards here, change Jack backend if necessary,
  # and perhaps tweak the desktop menu to make an appropriate mixer available

  amixer sset 'Master Mono' 90% unmute &> /dev/null
  amixer sset 'Master' 90% unmute &> /dev/null
  amixer sset 'PCM' 90% unmute &> /dev/null

  #TODO: Check for USB media and mount it, then make .bash_profile create a symlink to it
  clear
}

case "$1" in
  start)
    do_setup_live_environment
    ;;
esac
exit 0
