#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

do_setup_live_environment()
{
  chmod 0440 /etc/sudoers 
  mkdir -p /home/$LIVE_USERNAME
  groupadd admin
  useradd -u 1000 -g users -G storage,optical,audio,video,network,wheel,power,hal,lp,admin -d /home/$LIVE_USERNAME $LIVE_USERNAME
  passwd -d $LIVE_USERNAME &> /dev/null
  chown users:$LIVE_USERNAME /home/$LIVE_USERNAME
  su -c "cp -r /etc/skel/.[a-zA-Z0-9]* /home/$LIVE_USERNAME/" $LIVE_USERNAME
  su -c "cp -r /etc/skel/* /home/$LIVE_USERNAME/" $LIVE_USERNAME

  #Try to get a sensible volume set
  amixer sset 'Master Mono' 90% unmute &> /dev/null
  amixer sset 'Master' 90% unmute &> /dev/null
  amixer sset 'PCM' 90% unmute &> /dev/null

  #TODO: Check for USB media and mount it, then make .bash_profile create a symlink to it
}

case "$1" in
  start)
    do_setup_live_environment
    ;;
esac
exit 0
